### PR TITLE
Added RTG Support and Dimension ID Check

### PR DESCRIPTION
**Pull request by reteo**
COGActive now checks for "Realistic Terrain Generation" as well as ATG and the vanilla overworld.  

Additionally, in order to prepare for additional dimension oregen (some of which use "RandomLevelSource" for their oregen), now, all dimensions are now checked against both "dimension.generator" *and* "dimension.id".

### CODE REVIEW

**Comment by reteo** [comment]
For now, I'm going to cancel this; I was unaware of the dimension.generator.class test, and would like to try that to see if things can be a little more cleanly made.

**Comment by reteo** [comment]
Okay, the problem's been fixed, but for some reason, I am unable to submit a pull request.  I can't even seem to re-open this one. :(

**Comment by reteo** [comment]
Okay, the problem's been fixed, but for some reason, I am unable to submit a pull request.  I can't even seem to re-open this one. :(

**Comment by reteo** [comment]
Okay, the problem's been fixed, but for some reason, I am unable to submit a pull request.  I can't even seem to re-open this one. :(

**Comment by reteo** [comment]
Okay, the problem's been fixed, but for some reason, I am unable to submit a pull request.  I can't even seem to re-open this one. :(

**Comment by reteo** [comment]
Okay, the problem's been fixed, but for some reason, I am unable to submit a pull request.  I can't even seem to re-open this one. :(

**Comment by reteo** [comment]
Okay, the problem's been fixed, but for some reason, I am unable to submit a pull request.  I can't even seem to re-open this one. :(

**Comment by reteo** [comment]
Okay, the problem's been fixed, but for some reason, I am unable to submit a pull request.  I can't even seem to re-open this one. :(

**Comment by reteo** [comment]
Looks like the problem wasn't that I couldn't  open a pull request, but that for whatever reason, this page is not reloading when I submit forms.

**Comment by reteo** [comment]
Okay, I've fixed CustomOreGen_Default.xml, and all the other configurations, to check for chunk providers instead of dimension generators.  I've also added support for Realistic Terrain Generation.

**Comment by lawremi** [comment]
Why are so many empty lines added?

**Comment by reteo** [comment]
I've yet to figure out how to make the generator avoid adding a blank line for each dimension it does *not* generate.  Since the extra space doesn't harm the mod, I decided not to stress about it for now.

**Comment by reteo** [comment]
I've yet to figure out how to make the generator avoid adding a blank line for each dimension it does not generate ores for. Since the extra space doesn't harm the mod, I decided not to stress about it for now.

**Comment by reteo** [comment]
I've yet to figure out how to make the generator avoid adding a blank line for each dimension it does *not* generate ores for. Since the extra space doesn't harm the mod, I decided not to stress about it for now.

**Comment by reteo** [comment]
I've yet to figure out how to make the generator avoid adding a blank line for each dimension it does *not* generate ores for.  This was not very obvious when there were only three dimensions, but now that there are 14 different dimensions to choose from in the generator (see the thread or Sprocket's README), the space is a bit more noticeable.  Since the extra space doesn't harm the mod, I decided not to stress about it for now.

**Comment by reteo** [comment]
I've yet to figure out how to make the generator avoid adding a blank line for each dimension it does *not* generate ores for. This was not very obvious when there were only three dimensions, but now that there are 16 different dimensions to choose from in the generator (see the thread or Sprocket's README), the space is a bit more noticeable. Since the extra space doesn't harm the mod, I decided not to stress about it for now.

**Comment by reteo** [comment]
Oh, by the way, please make sure Keybounce gets the credit for the chunk provider class check; I did not even know that was possible until he gave me a swift kick in the pants. ;)

**Pull request merged**
