### PR TITLE
Preliminary 1.14 updates

### PR DESCRIPTION
**Pull request by Draco18s**

### CODE REVIEW

**Comment by Draco18s** [comment]
Conflict looks minor, looks like my branch would be the right resolution (getRainfall changed to getDownfall)

**Comment by Draco18s** [comment]
Oh also. The documentation for tags:
https://mcforge.readthedocs.io/en/1.13.x/utilities/tags/
Block Tags will likely come in real handy.

**Comment by lawremi** [comment]
Ok, thanks for the pointer. Forge looks a lot better documented these days.

**Comment by Draco18s** [comment]
The [1.13 primer](https://gist.github.com/williewillus/353c872bcf1a6ace9921189f6100d09a) has been pretty helpful, although there are a few things that changed names from 1.13 to 1.14 that trip me up here and there.

I forgot to do a mod.toml file, but it's [real easy](https://github.com/Draco18s/ReasonableRealism/blob/1.14.4/src/main/resources/META-INF/mods.toml). Its all the stuff that was split between the @Mod annotation and the mcinfo file (note that mine currently lists two mods and you'll only need the one). Its so easy that I pretty much went "let me fill in the info and see if it works, oh it did, how about that. Now I need to load two main mod files, let me take a stab in the dark, hey that worked."

**Comment by Draco18s** [comment]
And some potentially helpful information regarding oregen
https://gist.github.com/Barteks2x/41122efc766afdd47aeb457a3c19b275#gistcomment-2989342

**Comment by lawremi** [comment]
Ok. Just to set expectations, I'll be on an overseas business trip for the next 5 days but I should be able to start hacking on this after I get back.

**Comment by Draco18s** [comment]
No worries, enjoy your trip. I'm in no hurry.
Well, ok, a bit of a hurry. I would like to have COG before 1.15 comes out? ;)

**Pull request merged**
