### PR TITLE
1.14 new

### PR DESCRIPTION
**Pull request by Draco18s**
Lets try this again.
Gui fixes were largely the same, but there were some differences; easy to deal with.
Dealt with creating the event handler to remove ore features from biomes, which resolves a FIXME (old commented code left in place, though).

### CODE REVIEW

**Comment by lawremi** [comment]
Thanks. I'm a little wary to just comment out so much code. If we're commenting out code because we can't figure out how to compile it, perhaps we could mark it as such. In other cases, like removing the vanilla ore generation, we should just delete the code if we don't need it anymore.

The tag-based ore generator removal is interesting, and we could extend the config format to support blocking generation of ores instead of relying on substitution with stone. For now, let's just support the existing vanilla generation feature (there is no longer a check). Could we reuse BlockDescription to generalize the generator matching and thus reduce the current code duplication? That would make it easy to extend the config later. Nice job figuring out how the new feature stuff works.

**Comment by Draco18s** [comment]
Most of the commented out stuff has been superceded by new ways of doing things (`Button` now takes a method reference, which it invokes itself, `AbstractButton` has an `onPress` overridable method) and I just kept the code commented out in case something didn't function correctly (it would be easier to reference when fixing). The scrolling view is the bit that I wasn't sure how vanilla dealt with the buttons and left a TODO on it.

> The tag-based ore generator removal is interesting, and we could extend the config format to support blocking generation of ores

Certainly an idea. I went poking my nose into the generators and saw your comment about migrating the configs over to use the `FeatureConfig` system and went "I *really* don't want to touch this."

The main issue is that you'd have to remove the generators before a world is loaded, as once you load/create a world, vanilla spins off threads (and modifying the features list at that time would be a Bad Idea).

> Could we reuse BlockDescription to generalize the generator matching and thus reduce the current code duplication?

Maybe? BlockDescription still has a few TODOs and commented-out sections, so its not actually usable yet, but assuming it was I don't see why it *couldn't* be used as the matcher for feature removal. Either way I didn't expect my functions to survive to release, they were "here's something that'll remove the generators" that could be tweaked or rewritten depending on what was actually needed (which is why I pushed both and only one gets called).

> Nice job figuring out how the new feature stuff works.

Doing my best. I'm still not sure what I've figured out is how it was *intended* to be used, but it does *work.* Then again, vanilla loads a lot of structure data from NBT and there aren't any hooks to inject one's own structures (or at least, I was never able to find where vanilla actually reads the data from disk, supply my own values *and* have it work). In any case, "work" was all that was needed to get COG functional, as COG doesn't rely on specific pre-defined structures.

**Comment by lawremi** [comment]
Ok, thanks for this. I'll just need to carefully go through and review all the stuff that has been commented out.

**Comment by Draco18s** [comment]
Yep, of course. :)

**Pull request merged**
