### PR TITLE
1.12 Branch

### PR DESCRIPTION
**Pull request by Draco18s**
Not sure what branch of the base I point the PR at.

Anyway, here's the changes I made to get COG running on 1.12

Used `HasSky -> hasSkyLight`, still unsure about that one. 

Biome names changed to registry names (fortunately not many were affected beyond an enforcement to lower case). BOP thankfully used the same string for both the name and the registry name.

### CODE REVIEW

**Comment by lawremi** [comment]
Sorry for leaving this for so long. Could you just reissue this against the master branch? For some reason it is against the 1.10 branch, which of course causes all sorts of conflicts.

**Comment by Draco18s** [comment]
I can't do it right away, but soon. I've recently relocated and haven't set up my computer yet.

**Comment by lawremi** [comment]
Hi Draco,

Just a reminder about this. I think all that's needed is some button clicks in GitHub. Then we can get a 1.12 version out. Thanks!

**Comment by Draco18s** [comment]
Thanks for the reminder, my life's been chaos.

**Pull request closed without merging**
