### PR TITLE
Changed ores to match 1.10 version of AE2

### PR DESCRIPTION
**Pull request by reteo**
Applied Energistics changes have been made in the spreadsheet, Sprocket, and here.

### CODE REVIEW

**Comment by lawremi** [comment]
I should have looked at this one more carefully. It looks like the config now includes an option named `vanillaOreGen` which conflicts with the special option in CustomOreGen_Default.xml. Maybe you could use a different name for that option?

**Comment by reteo** [comment]
[This one?](https://github.com/lawremi/CustomOreGen/blob/27c524c69a882e7d37d0ea8a270859ca86a54a9e/src/main/java/CustomOreGen/Server/WorldConfig.java#L50)

**Comment by lawremi** [comment]
We can only have one definition in the configuration, so we'll probably drop it from CustomOreGen_Default.xml. Btw, I think `cleanUpVanilla` should default to the value of `vanillaOreGen` so that we do not waste time cleaning up when it's already disabled.

**Comment by reteo** [comment]
I'll try to have it updated in the next couple days.

**Pull request merged**
