### PR TITLE
Added biome sets for temperature, rainfall, and a couple terrain features.

### PR DESCRIPTION
**Pull request by reteo**
Temperatures:

* frozenTemp (below 0)
* coldTemp (Between 0 and 0.25)
* coolTemp (Between 0.25 and 0.5)
* warmTemp (Between 0.5 and 1)
* hotTemp (Between 1 and 2)

Rainfall:

* noRain (below 0)
* slightRain (Between 0 and 0.25)
* lightRain (Between 0.25 and 0.5)
* mediumRain (Between 0.5 and 1)
* heavyRain (Between 1 and 2)

Terrain Feature Biomes

* treeBiomes (All biomes that spawn trees)
* mountainBiomes (All biomes that generate mountain terrain)

### CODE REVIEW

**Comment by lawremi** [comment]
Note that if a biome matches multiple biome specifiers, the weights are summed. This means that some biomes, e.g., those of type "Hills" and also containing the name "Hills" will have twice the concentration of ores.

**Comment by reteo** [comment]
Hmmm.  Is there a way to set it to be boolean, so that no matter how many ways a biome is matched, it's simply matched, and not multiplied?

**Comment by reteo** [comment]
Okay, so now the sets have no weight at all by default; the weight has to be assigned by the configuration.  I hope this works. :-/

**Comment by lawremi** [comment]
I don't think a weight of zero is going to really help. It's true that there is no way to ensure disjointness without an "intersect" or "union" operation. The biome dictionary is a lost cause, for the most part, because it is used so inconsistently. Perhaps it is best to avoid it, instead relying on `treesPerChunk` for identifying biomes with trees and `heightVariation` for identifying hills. I can add support for that, along the lines of `minTemperature` and `maxTemperature`.

**Comment by reteo** [comment]
Alright.  I'll remove the code for now, and we'll see what comes up later... perhaps once you have the new system in place, I can set up some "reasonable defaults" in the config.

**Comment by reteo** [comment]
After doing some research, here are my findings on specific values that can be used for most of the major biome types:

Biomes:
• Tundra:
  ∘ Temperature: Cold (-2.0 to 0.15)
  ∘ Rainfall: Dry (0 to .05)
• Desert: 
  ∘ Temperature: Cool, Warm, and Hot (0.15 to 2.0)
  ∘ Rainfall: Dry (0 to .05)
• Boreal:
  ∘ Temperature: Cool (0.16 to 0.49)
  ∘ Rainfall: Slight and Normal (0.06 to 0.49)
• Temperate Grassland:
  ∘ Temperature: Warm (0.5 to 0.99)
  ∘ Rainfall: Slight (0.06 to 0.29)
• Deciduous Forest:
  ∘ Temperature: Warm (0.5 to 0.99)
  ∘ Rainfall: Normal (0.30 to 0.49)
• Temperate Rainforest:
  ∘ Temperature: Warm (0.5 to 0.99)
  ∘ Rainfall: Wet (0.5 to 1.0)
• Savanna
  ∘ Temperature: Hot (1.0 to 2.0)
  ∘ Rainfall: Slight (0.06 to 0.29)
• Tropical Seasonal Forest:
  ∘ Temperature: Hot (1.0 to 2.0)
  ∘ Rainfall: Normal (0.30 to 0.49)
• Tropical Rainforest:
  ∘ Temperature: Hot (1.0 to 2.0)
  ∘ Rainfall: Wet (0.5 to 1.0)

**Pull request closed without merging**
