### PR TITLE
Fixed Redstone and Lapis

### PR DESCRIPTION
**Pull request by reteo**
Redstone and Lapis Lazuli were too rare; between the low spawn and the vertical veins, it would be almost impossible to find any.  Updated the clusters so that they spawn more regularly.

### CODE REVIEW

**Comment by lawremi** [comment]
There are lots of seed and wireframe color changes. Could you remove those please? Also, have you play-tested this? An increase of over 100% is pretty dramatic.

**Comment by reteo** [comment]
I'll see what I can do; the seed and wireframe numbers are randomly generated per mod by Sprocket, I might have to update the utility to ensure seed numbers can be specified in the INI file.  Wireframe values can be set, and I'll do it once both have been restored.

**Comment by lawremi** [comment]
Seems weird to generate those randomly. For the colors, you could choose from a palette in a logical way, so that colors are distinct. For the seeds, they could just start from some offset (or randomly generate them based on the same seed, as I think you are suggesting).

**Comment by reteo** [comment]
The colors can be selected logically; however, I neglected to add them to the config files once I verified that the Sprocket RNG was working; Sprocket is designed to generate a random rgb hex code when no color is selected for the wireframe, in order to ensure there's at least a different color for each mod's oregen wireframe.

**Comment by lawremi** [comment]
I mean, if the color is not specified, the program can choose a logical default, like plotting software does.

**Comment by reteo** [comment]
You're going to have to explain, I'm not sure I follow.  How can there be a logical value when the program doesn't know anything about the ore it's generating the config for?  Or are you saying that it should just set a single "fix me" color?

**Comment by reteo** [comment]
Just to keep you updated, I've just finished manually setting all the wireframe colors for all the included mods.  I'll be working on configuring static seeds shortly.

**Pull request closed without merging**
