### PR TITLE
Update AppliedEnergistics.xml

### LINKED ISSUE #166: No AE2 quartz in 1.10
AE2 is detected, but the generation option doesn't want to switch from "no".

Probably the block names changed. I expect I'll update this with a solution later today, just wanted to mention the problem.

### PR DESCRIPTION
**Pull request by Baughn**
Fixes #166

I feel like it might be breaking a lot of other things, though. The .ini file in Sprocket doesn't quite match. But oh well, I'm sure you can figure it out.

---
This change is [Reviewable](https://reviewable.io/reviews/lawremi/customoregen/167)

### CODE REVIEW

**Comment by lawremi** [comment]
What do you mean by the ini file not quite matching?

**Comment by reteo** [comment]
Actually, the values placed there ("x * _default_") were specifically placed to ensure that Certus Quartz would not over or under-populate in reference to the vanilla settings.  It's not a good idea to replace the numbers with "_default_", as that would wipe out the ore's spawn balance.

**Comment by Baughn** [comment]
Right. Can those factors not be added to the .ini?

**Comment by reteo** [comment]
They can, and in the original ini, [they have](https://github.com/reteo/Sprocket/blob/master/configs/Examples/Standard/INI/AppliedEnergistics.ini).  If you use that file as the default to start tweaking, you can fix the ores without breaking the balance.

**Comment by Baughn** [comment]
Ahh. I used the "Blank" one; didn't spot Standard.

This one should be good.

**Comment by lawremi** [comment]
The changes look good, but they should really happen at the Sprocket ini level, so that we can continue to batch autogenerate the XML files.

**Comment by Baughn** [comment]
There wasn't an 1.10 branch of Sprocket, though. Is 'master' it?

**Comment by reteo** [comment]
Yes.  I "snapshot" the different versions of things.  Once it was obvious 1.2.26 was the last one to be released for 1.7.10, I snapshotted Sprocket, and now am setting up the master for 1.10.  Considering that I don't really play 1.10, however, I'm trusting others to actually test these things.

**Comment by reteo** [comment]
Additionally, I've already updated Applied Energistics, so if you can get a copy and test it, it should work correctly.

**Comment by lawremi** [comment]
Should be fixed via #169.

**Pull request closed without merging**
