### PR TITLE
Fixed drawWireframe, cleanup settings, refined clay distribution.

### PR DESCRIPTION
**Pull request by reteo**
Vanilla clay distribution is now corrected; it will avoid all ocean and savanna biomes, as well as all mountain, sandy, and snowy biomes, while doubling up in rivers and swamps.  Additionally, "drawWireframe" for each distribution now defaults to ":= drawWireframes" as defined in the default XML. (Fixing #175)

Note that while the "cleanup" option was originally visible, the cleanup step would not have run if the COG handling was disabled, since the check for "enabled" was set in the overall dimension configuration before any steps began.  I've fixed it now so that the cleanup option will not appear if the mod's oregen is disabled in COG.

### CODE REVIEW

**Comment by lawremi** [comment]
Another way to avoid dry biomes is to restrict on the rainfall amount. See https://github.com/lawremi/CustomOreGen/wiki/Biome-restriction. If rainfall is `<0.15f`, it could be considered dry. Post 1.7.10, there is even a type "dry".

**Comment by reteo** [comment]
Not a bad idea.  Testing the idea now.

**Comment by reteo** [comment]
Looks like we have a winner.

**Comment by lawremi** [comment]
Thanks @reteo . Your continued dedication to this project is appreciated.

**Pull request merged**
