### PR TITLE
Fix BlockDescriptor using BlockStates directly

### PR DESCRIPTION
**Pull request by Draco18s**
Fixes a crash attempting to put curved track states onto Powered Rail.
This is cleanly handled by the client (prints a stack trace and moves on), but not by the dedicated server.

### CODE REVIEW

**Comment by lawremi** [comment]
To clarify, this happens when using a regular expression that matches all meta values, while only some are valid? We should probably fix this in the `regexMatch()` method, where only the valid states are considered. It could just return an array with a value for every state (plus one for the wildcard), so the calling code is simpler.

**Comment by Draco18s** [comment]
I am unclear if its from the regex match, it could be.  Just that the original loop loops through all 16 metadata variants, expecting them to be valid.  The problem is that the Powered Rail uses the lower 3 for direction (of which only 6 of the 8 are valid) and so it tries to set SOUTH_EAST and SOUTH_WEST RailDirections which the BlockStateContainer rejects:

`    public static final PropertyEnum<BlockRailBase.EnumRailDirection> SHAPE = PropertyEnum.<BlockRailBase.EnumRailDirection>create("shape", BlockRailBase.EnumRailDirection.class, new Predicate<BlockRailBase.EnumRailDirection>() {`
`        public boolean apply(@Nullable BlockRailBase.EnumRailDirection p_apply_1_) {`
`            return p_apply_1_ != BlockRailBase.EnumRailDirection.NORTH_EAST && p_apply_1_ != BlockRailBase.EnumRailDirection.NORTH_WEST && p_apply_1_ != BlockRailBase.EnumRailDirection.SOUTH_EAST && p_apply_1_ != BlockRailBase.EnumRailDirection.SOUTH_WEST;`
`        }`
`    });`

**Comment by Draco18s** [comment]
Commenting here because this actually effects COG's ability to place blocks!

Dev, _with_ my change:

Nov 4 Release, _without_ my change:


Same world, same seed, same configs, same location.

I was seeing an issue where ores were not showing up in release, said "I know I made some alterations to the code, let me check what those were.  A handful of lines due to MCP mappings being slightly different and then this PR.

I undid the change that is this PR, regenerated the world, and...no ores!

**Comment by Draco18s** [comment]
Commenting to say that this is still an issue.

**Comment by lawremi** [comment]
After the change? Perhaps you could give me some way to reproduce the issue you're seeing.

**Comment by Draco18s** [comment]
Here's the change I made earlier to work around the issue, but is more strict than preferred. 
If you grab the older file, that's be the one that produces the error. 
https://github.com/Draco18s/ReasonableRealism/commit/1c99cd59819dffe158d7b7414b1a9b4b512d9097

**Comment by lawremi** [comment]
Well the commit above was meant to address that. Just to make sure, that did not work for you?

**Comment by Draco18s** [comment]
Correct. I've checked twice that I've got the same code you do.

**Comment by lawremi** [comment]
Thanks for staying on top of this and the simple reproducible example. Should be fixed now.

**Comment by Draco18s** [comment]
Sure thing.  I only knew it was "something" in my configs that did it (as the COG defaults are all fine). It was just a matter of figuring out what was making it fall into the bad branch.

**Pull request closed without merging**
